version: '3.8'

services:
  # Backend Service - MongoDB Atlas'a bağlanır
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: student_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      # MongoDB Atlas connection
      MONGODB_URI: mongodb+srv://canerbykdr:C.nemesis123@cluster0.9ffwk0b.mongodb.net/student-management-system?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: jwt_secret_key_production_123
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    networks:
      - app_network

  # Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: student_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge